version: "3"

services: 
  postgresql:
    image: postgres:14.1
    container_name: tryguessit_game_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
