name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndRunTests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: personal_site_db
          
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: false
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test src --filter FullyQualifiedName~.UnitTests --no-restore
    - name: Generate EntityFramework migrations bundle
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        cd /home/runner/work/TryGuessIt.Game/TryGuessIt.Game/
        dotnet ef migrations bundle -p ./src/TryGuessIt.Game.Persistence.Npgsql/TryGuessIt.Game.Persistence.Npgsql.csproj -s ./src/TryGuessIt.Game.WebApi/TryGuessIt.Game.WebApi.csproj -o 'efbundle_PersistedGrantDbContext.exe' --verbose
    - name: Run EntityFramework migrations
      run: |
        ./efbundle_TryGuessItIdentityDbContext.exe --connection 'User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=tryguessit_game;'
    - name: Run integration tests
      env: 
         ConnectionStrings__TryGuessIt_Game_GameDb: User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=tryguessit_game;
      run: dotnet test src --filter FullyQualifiedName~.IntegrationTests --no-restore