name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildAndRunTests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tryguessit_game
          
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Restore NuGet packages
      run: dotnet restore -r 'linux-x64'
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test --filter FullyQualifiedName~.UnitTests --no-restore
    - name: Generate EntityFramework migrations bundle
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        cd /home/runner/work/TryGuessIt.Game/TryGuessIt.Game/
        dotnet ef migrations bundle -p ./src/TryGuessIt.Game.Persistence.Npgsql/TryGuessIt.Game.Persistence.Npgsql.csproj -s ./src/TryGuessIt.Game.WebApi/TryGuessIt.Game.WebApi.csproj -o 'TryGuessId.Game.efbundle.exe' --verbose
    - name: Run EntityFramework migrations
      run: |
        ./TryGuessId.Game.efbundle.exe --connection 'User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=tryguessit_game;'
    - name: Run integration tests
      env: 
         ConnectionStrings__TryGuessIt_Game_GameDb: User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=tryguessit_game;
      run: dotnet test --filter FullyQualifiedName~.IntegrationTests --no-restore