name: Deploy Container App

on:
  workflow_dispatch:
  push:
    branches: [ ci/123-deployment-on-release ]


jobs:
  deploy-container-app:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/guexit/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_GUEXIT_PRD }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: guexit-prod-game
          resourceGroup: guexit-prod
          imageToDeploy: ghcr.io/guexit/guexit-game:1.17.0
