name: Deploy Container App

on:
  workflow_dispatch:
  push:
    branches: [ ci/123-deployment-on-release ]


jobs:
  deploy-container-app:
    name: Deploy Container App
    uses: Guexit/Guexit.Infrastructure/.github/workflows/templates/deploy-container-app.yml@ci/14-deploy-container-app-to-azure
    with:
      IMAGE_TO_DEPLOY_NAME: guexit-game:1.16.0
      CONTAINER_APP_NAME: guexit-prod-game
    secrets:
      AZURE_CREDENTIALS_GUEXIT_PRD: ${{ secrets.AZURE_CREDENTIALS_GUEXIT_PRD }}
