name: Publish Artifact

concurrency:
  group: PublishArtifact
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

# 3. Build docker image with the new version
# 4. Create a release on the repository with this tag

jobs:
  build-and-run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
    
  generate-new-version-tag:
    name: Generate new version tag
    needs: build-and-run-tests
    runs-on: ubuntu-latest
    outputs: 
      new-version: ${{ steps.calculate-new-version.outputs.new-version }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.buildSolutionAndRunTests.outputs.commit-hash }} 
          fetch-depth: 0
          
      - name: Calculate new version
        id: calculate-new-version
        run: ./.github/scripts/calculate_new_version.sh