name: Run Tests

on:
  workflow_call: 
  pull_request:
    branches: [ main ]
  push: 
    branches: [ main ]

jobs:
  buildSolutionAndRunTests:
    name: Build solution and run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: guexit_game
          
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK 8.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore NuGet packages
      run: dotnet restore -r 'linux-x64'
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test --filter FullyQualifiedName~.UnitTests --no-restore
    - name: Generate EntityFramework migrations bundle
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        cd /home/runner/work/Guexit.Game/Guexit.Game/
        dotnet ef migrations bundle -p ./src/Guexit.Game.Persistence.Npgsql/Guexit.Game.Persistence.Npgsql.csproj -s ./src/Guexit.Game.WebApi/Guexit.Game.WebApi.csproj -o 'Guexit.Game.efbundle.exe' --verbose
    - name: Run EntityFramework migrations
      run: ./Guexit.Game.efbundle.exe --connection 'User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=guexit_game;'
    - name: Run integration tests
      env: 
         ConnectionStrings__Guexit_Game_GameDb: User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=guexit_game;
      run: dotnet test --filter FullyQualifiedName~.IntegrationTests --no-build